pipelines:
  branches:
    master:
      - step:
          name: Build and package
          script:
            - apt-get update && apt-get install -y zip
            - zip code.zip handler.js
          artifacts:
            - code.zip
      - step:
          name: Update Lambda code
          script:
            - pipe: atlassian/aws-lambda-deploy:0.2.1
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                FUNCTION_NAME: 'your-function-name'
                ZIP_FILE: 'code.zip'